# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadCellControl.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GUI(object):
    def setupUi(self, GUI):
        GUI.setObjectName(_fromUtf8("GUI"))
        GUI.setEnabled(True)
        GUI.resize(703, 628)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GUI.sizePolicy().hasHeightForWidth())
        GUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(GUI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabs.setTabPosition(QtGui.QTabWidget.North)
        self.tabs.setMovable(False)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.calibrationTab = QtGui.QWidget()
        self.calibrationTab.setEnabled(True)
        self.calibrationTab.setObjectName(_fromUtf8("calibrationTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.calibrationTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.measuredValueLabel = QtGui.QLabel(self.calibrationTab)
        self.measuredValueLabel.setObjectName(_fromUtf8("measuredValueLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.measuredValueLabel)
        self.measuredValueSpinBox = QtGui.QDoubleSpinBox(self.calibrationTab)
        self.measuredValueSpinBox.setEnabled(True)
        self.measuredValueSpinBox.setWrapping(False)
        self.measuredValueSpinBox.setMinimum(-999999999.0)
        self.measuredValueSpinBox.setMaximum(999999999.0)
        self.measuredValueSpinBox.setProperty("value", 0.0)
        self.measuredValueSpinBox.setObjectName(_fromUtf8("measuredValueSpinBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.measuredValueSpinBox)
        self.realValueLabel = QtGui.QLabel(self.calibrationTab)
        self.realValueLabel.setObjectName(_fromUtf8("realValueLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.realValueLabel)
        self.realValueSpinBox = QtGui.QDoubleSpinBox(self.calibrationTab)
        self.realValueSpinBox.setMinimum(-999999999.0)
        self.realValueSpinBox.setMaximum(999999999.0)
        self.realValueSpinBox.setObjectName(_fromUtf8("realValueSpinBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.realValueSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.splitter = QtGui.QSplitter(self.calibrationTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.addSampleButton = QtGui.QPushButton(self.splitter)
        self.addSampleButton.setObjectName(_fromUtf8("addSampleButton"))
        self.removeSampleButton = QtGui.QPushButton(self.splitter)
        self.removeSampleButton.setObjectName(_fromUtf8("removeSampleButton"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.sampleTable = QtGui.QTableWidget(self.calibrationTab)
        self.sampleTable.setMaximumSize(QtCore.QSize(16777215, 175))
        self.sampleTable.setMidLineWidth(0)
        self.sampleTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.sampleTable.setAlternatingRowColors(False)
        self.sampleTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.sampleTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.sampleTable.setShowGrid(True)
        self.sampleTable.setColumnCount(2)
        self.sampleTable.setObjectName(_fromUtf8("sampleTable"))
        self.sampleTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sampleTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sampleTable.setHorizontalHeaderItem(1, item)
        self.sampleTable.horizontalHeader().setVisible(False)
        self.sampleTable.horizontalHeader().setCascadingSectionResizes(False)
        self.sampleTable.horizontalHeader().setDefaultSectionSize(115)
        self.sampleTable.horizontalHeader().setHighlightSections(True)
        self.sampleTable.horizontalHeader().setMinimumSectionSize(75)
        self.sampleTable.horizontalHeader().setSortIndicatorShown(False)
        self.sampleTable.horizontalHeader().setStretchLastSection(True)
        self.sampleTable.verticalHeader().setVisible(False)
        self.sampleTable.verticalHeader().setDefaultSectionSize(15)
        self.sampleTable.verticalHeader().setHighlightSections(True)
        self.sampleTable.verticalHeader().setMinimumSectionSize(15)
        self.sampleTable.verticalHeader().setSortIndicatorShown(False)
        self.sampleTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.sampleTable)
        self.calibrationPlot = PlotWidget(self.calibrationTab)
        self.calibrationPlot.setMinimumSize(QtCore.QSize(0, 200))
        self.calibrationPlot.setObjectName(_fromUtf8("calibrationPlot"))
        self.verticalLayout_2.addWidget(self.calibrationPlot)
        self.splitter_2 = QtGui.QSplitter(self.calibrationTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabs.addTab(self.calibrationTab, _fromUtf8(""))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.settingsTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_2 = QtGui.QFrame(self.settingsTab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.Scale = QtGui.QLabel(self.frame_2)
        self.Scale.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Scale.setObjectName(_fromUtf8("Scale"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Scale)
        self.scalesComboBox = QtGui.QComboBox(self.frame_2)
        self.scalesComboBox.setObjectName(_fromUtf8("scalesComboBox"))
        self.scalesComboBox.addItem(_fromUtf8(""))
        self.scalesComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.scalesComboBox)
        self.Baudrate = QtGui.QLabel(self.frame_2)
        self.Baudrate.setObjectName(_fromUtf8("Baudrate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Baudrate)
        self.baudrateComboBox = QtGui.QComboBox(self.frame_2)
        self.baudrateComboBox.setObjectName(_fromUtf8("baudrateComboBox"))
        self.baudrateComboBox.addItem(_fromUtf8(""))
        self.baudrateComboBox.addItem(_fromUtf8(""))
        self.baudrateComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.baudrateComboBox)
        self.SampleRate = QtGui.QLabel(self.frame_2)
        self.SampleRate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SampleRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SampleRate.setObjectName(_fromUtf8("SampleRate"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.SampleRate)
        self.sampleRateSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.sampleRateSpinBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.sampleRateSpinBox.setDecimals(1)
        self.sampleRateSpinBox.setMinimum(-1.0)
        self.sampleRateSpinBox.setMaximum(80.0)
        self.sampleRateSpinBox.setProperty("value", 10.0)
        self.sampleRateSpinBox.setObjectName(_fromUtf8("sampleRateSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sampleRateSpinBox)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.tabs.addTab(self.settingsTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabs)
        self.plotFrame = QtGui.QFrame(self.centralwidget)
        self.plotFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.plotFrame.setObjectName(_fromUtf8("plotFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.plotFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.currentReadingFrame = QtGui.QFrame(self.plotFrame)
        self.currentReadingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.currentReadingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.currentReadingFrame.setObjectName(_fromUtf8("currentReadingFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.currentReadingFrame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.currentReadingLabel = QtGui.QLabel(self.currentReadingFrame)
        self.currentReadingLabel.setObjectName(_fromUtf8("currentReadingLabel"))
        self.horizontalLayout_4.addWidget(self.currentReadingLabel)
        self.currentReadingLCD = QtGui.QLCDNumber(self.currentReadingFrame)
        self.currentReadingLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.currentReadingLCD.setObjectName(_fromUtf8("currentReadingLCD"))
        self.horizontalLayout_4.addWidget(self.currentReadingLCD)
        self.verticalLayout_3.addWidget(self.currentReadingFrame)
        self.plotWidget = PlotWidget(self.plotFrame)
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.verticalLayout_3.addWidget(self.plotWidget)
        self.plotControlFrame = QtGui.QFrame(self.plotFrame)
        self.plotControlFrame.setObjectName(_fromUtf8("plotControlFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.plotControlFrame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.autoRangeButton = QtGui.QPushButton(self.plotControlFrame)
        self.autoRangeButton.setObjectName(_fromUtf8("autoRangeButton"))
        self.horizontalLayout_2.addWidget(self.autoRangeButton)
        self.clearPlotsButton = QtGui.QPushButton(self.plotControlFrame)
        self.clearPlotsButton.setObjectName(_fromUtf8("clearPlotsButton"))
        self.horizontalLayout_2.addWidget(self.clearPlotsButton)
        self.autoscrollCheckBox = QtGui.QCheckBox(self.plotControlFrame)
        self.autoscrollCheckBox.setChecked(False)
        self.autoscrollCheckBox.setTristate(False)
        self.autoscrollCheckBox.setObjectName(_fromUtf8("autoscrollCheckBox"))
        self.horizontalLayout_2.addWidget(self.autoscrollCheckBox)
        self.verticalLayout_3.addWidget(self.plotControlFrame)
        self.horizontalLayout.addWidget(self.plotFrame)
        GUI.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(GUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 703, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuUnits = QtGui.QMenu(self.menuBar)
        self.menuUnits.setObjectName(_fromUtf8("menuUnits"))
        self.menuCalibrations = QtGui.QMenu(self.menuBar)
        self.menuCalibrations.setObjectName(_fromUtf8("menuCalibrations"))
        self.menuRecordings = QtGui.QMenu(self.menuBar)
        self.menuRecordings.setObjectName(_fromUtf8("menuRecordings"))
        GUI.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(GUI)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionN = QtGui.QAction(GUI)
        self.actionN.setCheckable(True)
        self.actionN.setChecked(True)
        self.actionN.setObjectName(_fromUtf8("actionN"))
        self.actionKg = QtGui.QAction(GUI)
        self.actionKg.setCheckable(True)
        self.actionKg.setObjectName(_fromUtf8("actionKg"))
        self.actionLbs = QtGui.QAction(GUI)
        self.actionLbs.setCheckable(True)
        self.actionLbs.setObjectName(_fromUtf8("actionLbs"))
        self.actionOpenCal = QtGui.QAction(GUI)
        self.actionOpenCal.setShortcut(_fromUtf8(""))
        self.actionOpenCal.setObjectName(_fromUtf8("actionOpenCal"))
        self.actionSaveCal = QtGui.QAction(GUI)
        self.actionSaveCal.setObjectName(_fromUtf8("actionSaveCal"))
        self.actionSaveCalAs = QtGui.QAction(GUI)
        self.actionSaveCalAs.setObjectName(_fromUtf8("actionSaveCalAs"))
        self.actionSave_2 = QtGui.QAction(GUI)
        self.actionSave_2.setObjectName(_fromUtf8("actionSave_2"))
        self.actionOpenRec = QtGui.QAction(GUI)
        self.actionOpenRec.setObjectName(_fromUtf8("actionOpenRec"))
        self.actionSaveRec = QtGui.QAction(GUI)
        self.actionSaveRec.setObjectName(_fromUtf8("actionSaveRec"))
        self.actionSaveRecAs = QtGui.QAction(GUI)
        self.actionSaveRecAs.setObjectName(_fromUtf8("actionSaveRecAs"))
        self.actionExportSnippet = QtGui.QAction(GUI)
        self.actionExportSnippet.setObjectName(_fromUtf8("actionExportSnippet"))
        self.menuUnits.addAction(self.actionN)
        self.menuUnits.addAction(self.actionKg)
        self.menuUnits.addAction(self.actionLbs)
        self.menuCalibrations.addAction(self.actionOpenCal)
        self.menuCalibrations.addAction(self.actionSaveCalAs)
        self.menuRecordings.addAction(self.actionOpenRec)
        self.menuRecordings.addAction(self.actionSaveRecAs)
        self.menuBar.addAction(self.menuUnits.menuAction())
        self.menuBar.addAction(self.menuCalibrations.menuAction())
        self.menuBar.addAction(self.menuRecordings.menuAction())

        self.retranslateUi(GUI)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        GUI.setWindowTitle(_translate("GUI", "Load Cell Controller", None))
        self.measuredValueLabel.setText(_translate("GUI", "Measured Value:", None))
        self.realValueLabel.setText(_translate("GUI", "Real Weight (N):", None))
        self.addSampleButton.setText(_translate("GUI", "Add Sample", None))
        self.removeSampleButton.setText(_translate("GUI", "Remove Sample", None))
        self.sampleTable.setSortingEnabled(False)
        item = self.sampleTable.horizontalHeaderItem(0)
        item.setText(_translate("GUI", "Measured Value", None))
        item = self.sampleTable.horizontalHeaderItem(1)
        item.setText(_translate("GUI", "Real Weight", None))
        self.tabs.setTabText(self.tabs.indexOf(self.calibrationTab), _translate("GUI", "Calibrate", None))
        self.Scale.setText(_translate("GUI", "Scale", None))
        self.scalesComboBox.setItemText(0, _translate("GUI", "Select...", None))
        self.scalesComboBox.setItemText(1, _translate("GUI", "Random Generator", None))
        self.Baudrate.setText(_translate("GUI", "Baudrate", None))
        self.baudrateComboBox.setItemText(0, _translate("GUI", "9600", None))
        self.baudrateComboBox.setItemText(1, _translate("GUI", "57600", None))
        self.baudrateComboBox.setItemText(2, _translate("GUI", "250000", None))
        self.SampleRate.setText(_translate("GUI", "Sample Rate", None))
        self.sampleRateSpinBox.setSuffix(_translate("GUI", " Hz", None))
        self.tabs.setTabText(self.tabs.indexOf(self.settingsTab), _translate("GUI", "Settings", None))
        self.currentReadingLabel.setText(_translate("GUI", "Current Reading (raw):", None))
        self.autoRangeButton.setText(_translate("GUI", "AutoRange", None))
        self.clearPlotsButton.setText(_translate("GUI", "Clear", None))
        self.autoscrollCheckBox.setText(_translate("GUI", "Autoscroll", None))
        self.menuUnits.setTitle(_translate("GUI", "Units", None))
        self.menuCalibrations.setTitle(_translate("GUI", "Calibrations", None))
        self.menuRecordings.setTitle(_translate("GUI", "Recordings", None))
        self.toolBar.setWindowTitle(_translate("GUI", "toolBar", None))
        self.actionN.setText(_translate("GUI", "N", None))
        self.actionKg.setText(_translate("GUI", "kg", None))
        self.actionLbs.setText(_translate("GUI", "lbs", None))
        self.actionOpenCal.setText(_translate("GUI", "Open...", None))
        self.actionSaveCal.setText(_translate("GUI", "Save", None))
        self.actionSaveCalAs.setText(_translate("GUI", "Save As...", None))
        self.actionSave_2.setText(_translate("GUI", "Save", None))
        self.actionOpenRec.setText(_translate("GUI", "Open...", None))
        self.actionSaveRec.setText(_translate("GUI", "Save", None))
        self.actionSaveRecAs.setText(_translate("GUI", "Save As...", None))
        self.actionExportSnippet.setText(_translate("GUI", "Export Snippet...", None))

from pyqtgraph import PlotWidget
